version: '3.7'

services:
  mysqlsrv:
    image: mysql:5.7
    ports:
      -"3306:3306"
    volumes:
      - /data/mysql-C:/var/lib/mysql
    container_name: toshiro-db
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: testedb
  
  networks:
    - minha-rede

  web:
    image: php:7.4-apache
    container_name: toshiro-web
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./nginx.conf:/etc/apache2/sites-available/000-default.conf

    ports:
      - "8080:80"
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge


    

  