version: '3.7'

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"

    container_name: mendes-web
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./nginx.conf:/etc/apache2/sites-available/000-default.conf
      
    networks:
      - minha-rede

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql-C:/var/lib/mysql
    container_name: mendes-db
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: testedb
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge